version: "3"

services:
  app:
    build: .
    container_name: docker-composer-app
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    links:
      - mariadb:database
    env_file: app/.env

  mariadb:
    image: mariadb:10.1.21
    container_name: docker-composer-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=docker-lamp
      - MYSQL_ROOT_PASSWORD=docker-lamp
