version: "3"

services:
  app:
    build: .
    container_name: docker-lamp-app
    ports:
      - "8080:80"
    volumes:
      - .:/app
    depends_on:
      - mariadb
    links:
      - mariadb:database
    env_file: .env

  mariadb:
    image: mariadb:10.1.21
    container_name: docker-lamp-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=docker-lamp
      - MYSQL_ROOT_PASSWORD=docker-lamp
